Every addition to true knowledge is an addition to human power

diff --git a/0x03-shell_variables_expansions/8-true_knowledge b/0x03-shell_variables_expansions/8-true_knowledge
--- a/0x03-shell_variables_expansions/8-true_knowledge
+++ b/0x03-shell_variables_expansions/8-true_knowledge
@@ -1,2 +1,10 @@
 #!/bin/bash
+if [ -z "$TRUEKNOWLEDGE" ]; then
+    echo "Error: The environment variable TRUEKNOWLEDGE is not set"
+    exit 1
+fi
+
 RESULT=$((128 + $TRUEKNOWLEDGE))
+
+echo $RESULT
+
